apiVersion: apps/v1
kind: Deployment
metadata:
  name: primuslearning
  labels:
    app: primuslearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primuslearning
  template:
    metadata:
      labels:
        app: primuslearning
    spec:
      containers:
        - name: primuslearning
          image: 361482797762.dkr.ecr.ap-south-1.amazonaws.com/primuslearning:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

